version: '3'

services:
  # hotel-booking-api:
  #   image: jackietian/hotel-booking-system-backend-api:latest
  #   ports:
  #     - 3000:3000
  #   environment:
  #     DB_HOST: mysql
  #     DB_USER: root
  #     DB_PASSWORD: root
  #     DB_NAME: test_db

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db