const actionTypes = {
    LOAD_IMAGES_REQUESTED: "LOAD_IMAGES_REQUESTED",
    LOAD_IMAGES_SUCCEEDED: "LOAD_IMAGES_SUCCEEDED",
    LOAD_IMAGES_FAILED: "LOAD_IMAGES_FAILED",
}

export default actionTypes
